name: Run automated tests

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install Chrome Browser
        run: sudo apt-get install google-chrome-stable
      
      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run Tests
        run: pytest -s -v tests/
